set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if (NOT DEFINED ETL_AVR_MCU OR ETL_AVR_MCU STREQUAL "")
    set(ETL_AVR_MCU "atmega328p")
endif()
set(ETL_AVR_MCU "${ETL_AVR_MCU}" CACHE STRING "Target AVR MCU")

find_program(AVR_GCC NAMES avr-gcc)
find_program(AVR_GXX NAMES avr-g++)
find_program(AVR_AR NAMES avr-gcc-ar avr-ar)
find_program(AVR_RANLIB NAMES avr-gcc-ranlib avr-ranlib)
find_program(AVR_OBJCOPY NAMES avr-objcopy)

foreach(tool AVR_GCC AVR_GXX AVR_AR AVR_RANLIB AVR_OBJCOPY)
    if (NOT ${tool})
        message(FATAL_ERROR "Required AVR tool not found: ${tool}")
    endif()
endforeach()

set(CMAKE_C_COMPILER "${AVR_GCC}")
set(CMAKE_CXX_COMPILER "${AVR_GXX}")
set(CMAKE_ASM_COMPILER "${AVR_GCC}")
set(CMAKE_AR "${AVR_AR}")
set(CMAKE_RANLIB "${AVR_RANLIB}")
set(CMAKE_OBJCOPY "${AVR_OBJCOPY}" CACHE FILEPATH "AVR objcopy tool")

set(AVR_COMMON_FLAGS_INIT "-mmcu=${ETL_AVR_MCU}")
set(CMAKE_C_FLAGS_INIT "${AVR_COMMON_FLAGS_INIT}")
set(CMAKE_CXX_FLAGS_INIT "${AVR_COMMON_FLAGS_INIT}")
set(CMAKE_ASM_FLAGS_INIT "${AVR_COMMON_FLAGS_INIT}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${AVR_COMMON_FLAGS_INIT}")
set(CMAKE_EXECUTABLE_SUFFIX ".elf")
